name: Build and Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install dependencies
        run: bundle install
      - name: Build
        run: JEKYLL_ENV=production bundle exec jekyll build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
